apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: helm-pixie
spec:
  package: ghcr.io/hops-ops/helm-pixie:{{ .Values.version }}
{{- if .Values.skipDependencyResolution }}
  skipDependencyResolution: true
{{- end }}
{{- if .Values.skipDependencyResolution }}
---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: hops-ops-helm-pixierender
spec:
  package: ghcr.io/hops-ops/helm-pixie-render:{{ .Values.version }}
{{- end }}
